openapi: 3.1.0
info:
  title: Correlation App API
  description: API to manage and query correlations between assets.
  version: 1.0.0
servers:
  - url: "https://{server}/v1"
    variables:
      server:
        default: correlation
  - url: "https://{environment}.eliona.io/apps/correlation/api/v1/"
    variables:
      environment:
        default: name
paths:
  /correlate/{correlation_id}:
    post:
      summary: Correlate assets
      description: Fetches correlation request by ID and computes correlations between specified assets.
      operationId: correlate_assets
      parameters:
        - name: correlation_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully computed correlations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  assets:
                    type: array
                    items:
                      $ref: "#/components/schemas/AssetAttribute"
                  lags:
                    type: array
                    items:
                      type: object
                      additionalProperties:
                        type: integer
                  start_time:
                    type: string
                    format: date-time
                  end_time:
                    type: string
                    format: date-time
                  correlation:
                    type: object
                    additionalProperties:
                      type: number
                  report_html:
                    type: string
        "404":
          description: Correlation request not found.
        "500":
          description: Error computing correlations.
  /correlate-children/{correlation_id}:
    post:
      summary: Correlate asset children
      description: Fetches correlation request by ID, retrieves child assets, and computes correlations.
      operationId: correlate_asset_children
      parameters:
        - name: correlation_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully computed correlations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  assets:
                    type: array
                    items:
                      $ref: "#/components/schemas/AssetAttribute"
                  lags:
                    type: array
                    items:
                      type: object
                      additionalProperties:
                        type: integer
                  start_time:
                    type: string
                    format: date-time
                  end_time:
                    type: string
                    format: date-time
                  correlation:
                    type: object
                    additionalProperties:
                      type: number
                  report_html:
                    type: string
        "404":
          description: Correlation request not found.
        "500":
          description: Error computing correlations.
  /in-depth-correlation/{correlation_id}:
    post:
      summary: In-depth correlation
      description: Fetches correlation request by ID and computes in-depth correlations between exactly two assets/attributes.
      operationId: in_depth_correlation
      parameters:
        - name: correlation_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully computed in-depth correlations.
          content:
            application/json:
              schema:
                type: object
                properties:
                  assets:
                    type: array
                    items:
                      $ref: "#/components/schemas/AssetAttribute"
                  lags:
                    type: array
                    items:
                      type: object
                      additionalProperties:
                        type: integer
                  start_time:
                    type: string
                    format: date-time
                  end_time:
                    type: string
                    format: date-time
                  correlation:
                    type: object
                    additionalProperties:
                      type: number
                  scatter_result_columns:
                    type: array
                    items:
                      type: string
                  report_html:
                    type: string
        "400":
          description: Invalid request (e.g., not exactly two assets).
        "404":
          description: Correlation request not found.
        "500":
          description: Error computing in-depth correlations.
components:
  schemas:
    LagUnit:
      type: string
      enum:
        - seconds
        - minutes
        - hours
        - days
        - months
        - years
    AssetAttribute:
      type: object
      properties:
        asset_id:
          type: integer
        attribute_name:
          type: string
          nullable: true
        diff:
          type: boolean
          nullable: true
      required:
        - asset_id
    CorrelationRequest:
      type: object
      properties:
        assets:
          type: array
          items:
            $ref: "#/components/schemas/AssetAttribute"
        lags:
          type: array
          items:
            type: object
            additionalProperties:
              type: integer
        start_time:
          type: string
          format: date-time
          nullable: true
        end_time:
          type: string
          format: date-time
          nullable: true
        to_email:
          type: string
          format: email
          nullable: true
      required:
        - assets
